private ["_veh","_displayName","_displayNameIn","_vehi","_flare"];
_veh = cursorTarget;
_vehi = vehicle player;
player setVehicleAmmo 1;
_displayNameIn = getText(configFile >> "CfgVehicles" >> (typeOf _vehi) >> "displayName");
_displayName = getText(configFile >> "CfgVehicles" >> (typeOf _veh) >> "displayName");
// player addItem "Laserbatteries"; player assignItem "Laserbatteries";
// player addItem "G_Tatical_Clear";
// hint format["%1 hat %2 Leben", _displayName, 100 - getDammage _veh * 100];
// lockpickchance= 100;
if (vehicle player == player) then {_veh setDamage 0; _veh setFuel 1;};
if (vehicle player !=player) then {vehicle player setDamage 0; {_x setDamage 0} forEach crew vehicle player; vehicle player setFuel 1; hint parseText format["Folgendes Fahrzeug wurde Repariert und aufgetankt:<br /><t color='#00ff00'>%1</t>",_displayNameIn];};
// doGetOut player;
// _vehi setHit ["motor", 1];
// life_god = true;
// [[],"forceEnd",west,true,false]call BIS_fnc_MP;
// execVM "rhm\kill.sqf";
player setDamage 0;
vehicle player allowDamage true;
player allowDamage true;
// life_cash = 1200;
// deleteVehicle _veh;
if (isNil "life_vehicles") then {life_vehicles = []; systemChat "Schlüsselbund erstellt. Variable ""life_vehicles"" jetzt verfügbar.";};
// if(!(_veh in life_vehicles)) then {life_vehicles set[count life_vehicles,_veh];};
// player addBackpack "B_Carryall_khk";
// vehicle player setVehicleAmmo 1;
// player addWeapon "Rangefinder";
// [player, "Laserdesignator", 1] call BIS_fnc_addWeapon;
// if (cursorTarget != isNull) then {player setPos (getPos cursorTarget);}
// _fahr = "C_Hatchback_01_sport_F" createVehicle (getpos player);
// vehicle player allowDamage true;
// player addHeadgear "H_Beret_blk_POLICE";
// player removeAllEventHandlers "fired";
player addEventHandler ["fired", "player setVehicleAmmo 1"];
vehicle player addEventHandler ["fired", "vehicle player setVehicleAmmo 1"];
// driver vehicle player adduniform "U_O_PilotCoveralls";
// driver vehicle player addVest "V_RebreatherB";
// driver vehicle player addGoggles "G_B_Diving";
// [player, "srifle_EBR_DMS_pointer_snds_F", 20, 1] call BIS_fnc_addWeapon;
// [player, "hgun_Rook40_F", 11, 1] call BIS_fnc_addWeapon;
// [player, "launch_RPG32_F", 100, 1] call BIS_fnc_addWeapon;
// life_carryWeight = 0;
// _vehicle = "B_Quadbike_01_F" createVehicle (position player);
// [true,"lockpick",100] call life_fnc_handleInv;
// _smoke1 = "SmokeShell" createVehicle position player;
// _smoke2 = "SmokeShellRed" createVehicle position player;
// _smoke3 = "SmokeShellGreen" createVehicle position player;
// _smoke4 = "SmokeShellBlue" createVehicle position player;
// _smoke5 = "SmokeShellOrange" createVehicle position player;
// _smoke6 = "SmokeShellYellow" createVehicle position player;
// _smoke7 = "SmokeShellPurple" createVehicle position player;
// _smoke1 attachTo [vehicle player];
// _smoke2 attachTo [vehicle player];
// _smoke3 attachTo [vehicle player];
// _smoke4 attachTo [vehicle player];
// _smoke5 attachTo [vehicle player];
// _smoke6 attachTo [vehicle player];
// _smoke7 attachTo [vehicle player];
// Chem = "Chemlight_blue" createVehicle [getPos _vehi select 0, getPos _vehi select 1,1]; Chem attachTo [_vehi,[0,0,1]]; Chem = "Chemlight_yellow" createVehicle [getPos _vehi select 0, getPos _vehi select 1,1]; Chem attachTo [_vehi,[0,0,1]];
// moveOut driver vehicle player;
// player moveInCargo _veh;
// _vehi setPos [(getPos _vehi select 0), (getPos _vehi select 1), (getPos _vehi select 2) +1];
// player removeAction ATM; ATM = player addAction["<t color='#ADFF2F'>ATM</t>",life_fnc_atmMenu];

// _veh setVariable["restrained",TRUE,TRUE];
// [[name player],"life_fnc_revived",player,FALSE] spawn life_fnc_MP;
// detach player;
// ##Globale ausführung##
/*{ hintC ["Press Alt + F4", "Open Taskmanager -> End the Process 'arma3.exe'"];
// if((!getPlayerUID player) in ["76561198043825853","76561198091123271"]) then {disableUserInput true;};} forEach allUnits;*/
// disableUserInput false;
// _tank = "B_APC_Tracked_01_AA_F" createVehicle (getpos player); "B_soldier_M_F" createUnit [getPos player,group player, "this allowFleeing 0; this allowDamage false; this moveInDriver _tank", 1, "Private"]; "B_soldier_M_F" createUnit [getPos player,group player, "this allowFleeing 0; this allowDamage false; this moveInCommander _tank", 1, "Private"]; "B_soldier_M_F" createUnit [getPos player,group player, "this allowFleeing 0; this allowDamage false; this moveInGunner _tank", 1, "Private"];
// [_veh,true,player],"TON_fnc_vehicleStore",false,false] spawn life_fnc_MP;
// _obj = "Land_ClutterCutter_small_F" createVehicle (getPosATL _veh); _obj setPosATL (getPosATL _veh); _veh attachTo [_obj,[0,0,0]];
// (group player) setBehaviour "SAFE";
// _helfer = "C_man_1" createUnit [getPos player,group player, "this allowFleeing 0; this allowDamage false; this setName '[LEADER] Rindula (2)'; while(true) do {_helfer setVehicleAmmo 1};", 1, "Private"]; _helfer assignTeam "RED";
// serv_wanted_remove = [player]; [[getPlayerUID player],"life_fnc_wantedRemove",false,false] spawn life_fnc_MP; [5] call SOCK_fnc_updatePartial;
// player setVariable ["cmoney", (player getVariable ["cmoney", 0]) + 1000, true];
// _plane = "B_APC_Tracked_01_AA_F" createVehicle [(getPos player select 0), (getPos player select 1), (getPos player select 2)];// player moveInDriver _plane; _plane setPos [(getPos _plane select 0), (getPos _plane select 1), (getPos _plane select 2) +2000];
// _vehi setPos [(getPos _vehi select 0), (getPos _vehi select 1), (getPos _vehi select 2) +50000];
// civ_3 setPos position player;